version: "3"

services:
  node:
    image: node:16
    container_name: express_middlewares
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000

networks:
  default:
    name: express_middlewares_net
